// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LightService.proto

package grpc.services.light;

public interface LightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Light.LightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightId = 1;</code>
   * @return The lightId.
   */
  java.lang.String getLightId();
  /**
   * <code>string lightId = 1;</code>
   * @return The bytes for lightId.
   */
  com.google.protobuf.ByteString
      getLightIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 intensity = 3;</code>
   * @return The intensity.
   */
  int getIntensity();
}
